### PR TITLE
🐛 Fix current markdown detection bug

### PR DESCRIPTION
**Pull request by EssamWisam**
I remember that @Iten-No-404 had a mechanism in place that would detect if loading LinkedIn image has failed and render the thumb if it has. It turns out that reason it didn't work (hence, squished images) was that the `currentMarkdown` when in the courses page was `./department/...` while `../department` was what's in the if check. I don't know when did that change but I believe it worked correctly when it was first implemented.

This is meant to be a temporary measure until @KnockerPulsar finds time to integrate the LinkedIn scraping feature he worked on.

### CODE REVIEW

**Comment by EssamWisam** [comment]
Hmmm. perfectly fixes it offline but squished images still show up on initial load for some reason. Will try to evade making the LinkedIn request in the first place to see if this solves it.

**Comment by EssamWisam** [comment]
Didn't fix it so I reverted.

**Comment by EssamWisam** [comment]
Made one more commit to force the image to take height in all cases so that even if it fails to load it doesn't squish and stays circular.

**Comment by EssamWisam** [comment]
@Iten-No-404 merge at your leisure should this PR make sense.

**Comment by Iten-No-404** [comment]
> Could also be that internet is faster at your side.

I doubt it but maybe.
> The check I do is launch the website from an incognito tab so force the browser not to use any cache.

I sometimes launched it in incognito mode and when just reloading the page, I do a deep reload.

> I find it comical that they want users to pay to be able to invite...

Many companies monetize the most basic features these days...🤦🏻‍♀️
> I can assure you that for me the behaviour was consistent across both.

Alright, how about trying again in a few hours? The internet speed is bound to be different then. 
Also, I tried a couple of times more and I noticed something. Sometimes, about only the first half of the list loads perfectly while the second half barely loads.

image

I can merge this PR and try it out a bit more on the Vercel deployment instead. Either way, it's much better than the squished images. Nice work.

**Comment by EssamWisam** [comment]
> Also, I tried a couple of times more and I noticed something. Sometimes, about only the first half of the list loads perfectly while the second half barely loads.

Yes, the ones that barely load correspond to squished images (now white disks). This should no longer happen upon refresh or visiting site again from same browser or at least this is what happens to me.

**Comment by Iten-No-404** [comment]
Tried a couple of times in both deployments and the squished images bug doesn't happen at all which is good news.
I have noticed that Vercel is a bit slower at loading the images than Netlify. Nonetheless, the bug doesn't occur and at worst some of the images (in the second half of the list) aren't loaded and appear as white circles instead which is still better than the bug.

> This should no longer happen upon refresh or visiting site again from same browser or at least this is what happens to me.

Indeed, that's what I have experienced as well.

**Comment by EssamWisam** [comment]
Iten, let me elaborate, I do expect the squished images bug not to occur because I modified the code so that instead of the image being "squished", it becomes a white disk as in my comments above. So this converts the squished images bug into empty images bug.

What I was saying earlier is that the empty images bug happens for me only in the initial load from an icognito tab/new browser. It also only happens starting from about half the list like you showed. 

> Indeed, that's what I have experienced as well.

Okay. Makes sense now.

**Pull request merged**
