### PR TITLE
✨ Add class 2021

### PR DESCRIPTION
**Pull request by EssamWisam**
This adds the English and Arabic class list for 2021.

### CODE REVIEW

**Comment by EssamWisam** [comment]
@Iten-No-404 could you kindly run the LinkedIn script so it populates their information (if you have time). I have been running into space issues on my machine and lack a chrome browser.

**Comment by Iten-No-404** [comment]
> @Iten-No-404 could you kindly run the LinkedIn script so it populates their information (if you have time). I have been running into space issues on my machine and lack a chrome browser.

@EssamWisam, I am currently at work and consequently don't have my personal laptop with me. So, I will run it once I get home insha'allah.

Also, did you manually search for the LinkedIn profiles or did you use a tool or something?

**Comment by Iten-No-404** [comment]
@EssamWisam, it is ready to be merged. 

I wanted to note however that the script didn't manage to extract the `current position` for Omar Salah for some reason even though it extracted his picture and title correctly. So, I wrote it manually for now.

**Comment by EssamWisam** [comment]
@Iten-No-404 No big deal just minor random errors. Thank you so much for the effort 🙏.

**Pull request merged**
