### PR TITLE
🚑 Fixing the start script #22

### PR DESCRIPTION
**Pull request by EssamWisam**
After getting the impression that Vercel didn't really help that much with availability, I tried deploying on Cloudflare where I perceived an SSL error which reminded me of the openssl error that one gets when they do a bare `npm start`:

- This lead me to try to fix that openssl error without modifying the start script
- Was as easy as upgrading React and WebPack

My expectations are that this fixes it for windows as well (and hopefully linux #22). @Iten-No-404 could you please confirm and merge if it indeed does so I can go back to CloudFlare.

### CODE REVIEW

**Comment by EssamWisam** [comment]
I think the builds are failing because they need to use a bare `npm run build` which is not how I set them up so we can ignore that. What I would like to know now if possible is whether a bare `npm start` runs the project successfully on Windows.

**Comment by Iten-No-404** [comment]
> @Iten-No-404 could you please confirm and merge if it indeed does so I can go back to CloudFlare.


> What I would like to know now if possible is whether a bare `npm start` runs the project successfully on Windows.

No problem, I'll try running it. Give me a couple of minutes.

**Comment by Iten-No-404** [comment]
> I think the builds are failing because they need to use a bare `npm run build` which is not how I set them up so we can ignore that. What I would like to know now if possible is whether a bare `npm start` runs the project successfully on Windows.

@EssamWisam , I cloned the branch on Windows and it ran with `npm start` just fine. It complied with warnings but no errors.

**Comment by EssamWisam** [comment]
Alright. Could you take off the `start_win` and commit so we merge this. 

I assume you have no access to Linux, eh?

**Comment by Iten-No-404** [comment]
> Alright. Could you take off the `start_win` and commit so we merge this.

Sure.

> I assume you have no access to Linux, eh?

I have dual-boot actually, so I could try it on Ubuntu. It might take me some minutes to switch between to Ubuntu though.

**Comment by EssamWisam** [comment]
giphy
Take your time 🙏.

**Comment by Iten-No-404** [comment]
Running on Ubuntu using `npm start` is successful as expected since the command is the original one now (i.e. `react-scripts start`).

@EssamWisam, the deployments are all not building correctly. Is there anything I can help with regarding that?

**Comment by EssamWisam** [comment]
> Running on Ubuntu using `npm start` is successful as expected since the command is the original one now (i.e. `react-scripts start`).

Thank you so much. We can now also close Tarek's issue and update the readme to remove the `start_win` part.

> @EssamWisam, the deployments are all not building correctly. Is there anything I can help with regarding that?

I assume it's as easy as going there and modifying the build script by excluding the old exports. Will let you know if help is needed beyond that. I think to test it we will have to merge this PR first so let's be optimistic and see what happens.

**Pull request merged**
