### PR TITLE
docs: Add class of 2020 Arabic and English yaml files

### PR DESCRIPTION
**Pull request by OsamaNabih**

### CODE REVIEW

**Comment by Iten-No-404** [comment]
@OsamaNabih, Thank you for your time and valuable contribution.
I will run the LinkedIn scraping script on the added file before merging.

**Comment by EssamWisam** [comment]
> @OsamaNabih, Thank you for your time and valuable contribution. I will run the LinkedIn scraping script on the added file before merging.

Thank you, Iten. I was discussion with Eng. Osama something regarding the markdown field because he contacted me regarding it so let's wait to resolve this before merging.

Thoughts are either to drop the markdown field in all yamls and let it be the constant ` You can know more about Ahmed and reach him out by visiting his [LinkedIn]()` or to keep it for added flexibility (e.g., a class wanting to write something different or someone in that class wants to write their bio).

**Comment by Iten-No-404** [comment]
> Thank you, Iten. I was discussion with Eng. Osama something regarding the markdown field because he contacted me regarding it so let's wait to resolve this before merging.

Sure. I already noticed this issue and did a small fix for it.

> Thoughts are either to drop the markdown field in all yamls and let it be the constant ` You can know more about Ahmed and reach him out by visiting his [LinkedIn]()` or to keep it for added flexibility (e.g., a class wanting to write something different or someone in that class wants to write their bio). In the latter case, we can also let ` You can know more about Ahmed and reach him out by visiting his [LinkedIn]()` to be constant and markdown to show below it.

I say we keep the `markdown` key for flexibility and add a check that adds the LinkedIn link in the format similar to what we are used to if something else is written in it. You can the logic below. I have already committed it a couple of minutes ago but I didn't push it yet in case there's any other pushes on Osama's end. For example:

- If the LinkedIn link for the student isn't available and the markdown is also empty, we'll show the following: `"رابط Linked غير معلوم."` or `"LinkedIn link for this student is unknown."`.
- If the LinkedIn link isn't available but there's text in the markdown, we'll show the Markdown text as well as the above text.
- If the Markdown text doesn't contain the string `[LinkedIn]()`, we'll show the Markdown followed by `"You can know more about " + person.name.split(" ")[0] + " and reach out by visiting [LinkedIn](" + person.linkedin_url + ")"` or `"يمكنك معرفة المزيد عن " + person.name.split(" ")[0] + " والتواصل من خلال زيارة [LinkedIn](" + person.linkedin_url + ")."`

I already implemented the above since errors occurred when opening the modals.

I also finished running the script on the C2020.yaml and added a few students that were present in one file (ex: Eng. version) but missing in the other. Lastly, I added `C20XX.yaml` and `C20XX_ar.yaml` as templates.

@OsamaNabih, please let me know if you are going to push any more commits, if not, then I will push the changes I have done. 
@EssamWisam, let me know your thoughts as well.

**Comment by EssamWisam** [comment]
Thanks for the impressive work @Iten-No-404. I assume your last case also handles the case where the markdown field doesn't exist at all (equivalent to being empty). If so, I like this resolution but we should document the behaviour and whole idea of LinkedIn feature. Once we merge this, I will do this in a separate PR and tag you.

**Comment by Iten-No-404** [comment]
> Thanks for the impressive work @Iten-No-404. 

Don't mention it, @EssamWisam.

> I assume your last case also handles the case where the markdown field doesn't exist at all (equivalent to being empty). 

Yes, that is handled as well as other similar cases. I just didn't mention all the possibilities for brevity.
 
> If so, I like this resolution but we should document the behaviour and whole idea of LinkedIn feature.

Document it as in the README file? It needs some modifications indeed.

> Once we merge this, I will do this in a separate PR and tag you.

Sure, no problem.

**Comment by OsamaNabih** [comment]
I agree with @Iten-No-404 suggestion's, thanks for the work. 
Looks good to me. You can proceed.
Sorry about the inconsistency between the 2 YAML files.

**Comment by Iten-No-404** [comment]
> I agree with @Iten-No-404 suggestion's, thanks for the work. 
> Looks good to me. You can proceed.
> Sorry about the inconsistency between the 2 YAML files.

It wasn't much of an issue, don't worry about it. Thank you again for your contribution. 🫡

**Pull request merged**
